malloydata/malloy-explorer

dev/Query.tsx
dev/Source.tsx
src/components/MalloyExplorerProvider.tsx
src/components/QueryPanel/QueryEditor.tsx
src/index.ts

Export TooltipProvider in our own wrapper so we can avoid having to reference radix outside of our bundle.

Wrap tooltip provider

---

src/components/QueryPanel/Parameters.tsx
src/components/QueryPanel/Query.tsx
src/components/QueryPanel/QueryEditor.tsx
src/components/QueryPanel/operations/NestOperation.tsx
src/components/primitives/Button.tsx
src/components/primitives/CollapsiblePanel.tsx
src/components/primitives/styles.ts
src/components/styles.ts

Following the [design mocks](https://www.figma.com/design/5k0OF2dysA5MyBwW9aEJGv/%E2%93%82%EF%B8%8F-Malloy-MVP?node-id=1119-54233&m=dev), update the Query Panel to include collapsible subpanels. In some cases, moves interaction such as clearing the query up into the 'more actions' menu of the bar.

Update Query panel to use Collapsible Panels for each section

---

src/components/primitives/tokens/styles.ts

It looks like the `position: relative` got dropped from the styles when it moved out of the Token file, causing the absolutely-positioned child to fill the entire page instead of the component ony.

Keep the token button inside the token

---

src/components/QueryPanel/AddMenu/AddFieldItem.tsx
src/components/QueryPanel/AddMenu/AddOrderBy.tsx

Show a helpful tooltip when the Order By menu item is disabled.

Add a disabled message to the Order By menu item

---

src/components/HoverCard.tsx
src/components/QueryPanel/QueryPanel.tsx
src/components/SourcePanel/FieldTokenWithActions.tsx
src/components/SourcePanel/SourcePanel.tsx
src/components/primitives/BadgeForField.tsx

First pass at hover cards.
There are a few known issues that I'll follow up with fixes for, such as the path missing the root element and the metadata or search index content not being included. Furthermore, if a description is not found, one is made up which will also change.

First pass at Hover Cards in the Source panel

---

src/components/HoverCard.tsx
src/components/SourcePanel/FieldGroupList.tsx
src/components/SourcePanel/utils.ts

Correctly include the root source in the path and exclude the property name which is rendered just below.

Fix path computation for hover cards

---

src/components/QueryPanel/LiteralValueEditor.tsx
src/components/QueryPanel/Visualization.tsx
src/components/filters/PillInput.tsx
src/components/filters/StringFilterToken.tsx
src/components/primitives/tokens/EditableToken.tsx
src/components/primitives/tokens/SelectorToken.tsx

Consistently use `customStyle` for things inside token groups, drill down customStyle for more complex tokens.

Fix up a bunch of token styling

---

src/components/MalloyExplorerProvider.tsx
src/components/QueryPanel/QueryEditor.tsx
src/components/QueryPanel/QueryPanel.tsx
src/components/QueryPanel/Source.tsx
src/components/SourcePanel/SourcePanel.tsx
src/contexts/ExplorerPanelsContext.ts

Add a context for managing shared UI state and a button to close the source panel and a button to open it again.

Add open/close logic on the source panel

---

dev/MalloyExplorer.tsx
src/components/MalloyExplorerProvider.tsx
src/components/QueryPanel/QueryEditor.tsx
src/components/QueryPanel/Source.tsx
src/components/SourcePanel/SourcePanel.tsx
src/contexts/ExplorerPanelsContext.ts

The QueryEditor is designed to be a stand-alone editor if necessary, it shouldn't be tied to the Source panel state.

Don't assume the existence of the source panel

---

dev/sample_models/example_model.ts
src/components/ResultPanel/ResultDisplay.tsx
src/components/ResultPanel/ResultPanel.tsx

Behavior change here is loading messages stay centered in parent container. 
Results still scroll as before

center result loading indicator

---

src/components/ResultPanel/ResultPanel.tsx

Also adds a `title` based tooltip for informational purposes.

Add disabled status for tabs

---

src/components/ResultPanel/ResultPanel.tsx
src/components/primitives/syntax_highlighting/transformers/lineNumberTransformer.ts

1. Add a cursor to the 'revert' link
2. Disable text selection on line numbers

Small Results panel styling tweaks

---

src/components/QueryPanel/ViewDefinition.tsx
src/components/ResultPanel/EmptyQueryDisplay.tsx
src/components/primitives/CollapsibleListItem.tsx

1. Remove the 'pointer' on hover over the 'view' card collapsible header
2. Align the items in the Sources panel with the chevron to save horizontal space per item 4 [here](https://docs.google.com/document/d/1Fix6-Aiw27jkjHOzId5dM7z4gE8W2C0SOl-uyQBl9_Y/edit?tab=t.0)
3. Make the empty state results panel height: 100% so it does not cause the page to grow

Various UX changes

---

src/components/QueryPanel/AddMenu/AddAggregate.tsx
src/components/QueryPanel/AddMenu/AddEmptyNest.tsx
src/components/QueryPanel/AddMenu/AddFieldItem.tsx
src/components/QueryPanel/AddMenu/AddGroupBy.tsx
src/components/QueryPanel/AddMenu/AddLimit.tsx
src/components/QueryPanel/AddMenu/AddMenu.tsx
src/components/QueryPanel/AddMenu/AddOrderBy.tsx
src/components/QueryPanel/AddMenu/AddView.tsx
src/components/QueryPanel/AddMenu/AddWhere.tsx
src/components/QueryPanel/AddMenu/FieldList.tsx
src/components/QueryPanel/AddMenu/FieldMenu.tsx
src/components/QueryPanel/Operations.tsx
src/components/QueryPanel/Query.tsx
src/components/QueryPanel/operations/AggregateOperations.tsx
src/components/QueryPanel/operations/GroupByOperations.tsx
src/components/QueryPanel/operations/LimitOperation.tsx
src/components/QueryPanel/operations/NestOperation.tsx
src/components/QueryPanel/operations/OperationActionTitle.tsx
src/components/QueryPanel/operations/OrderByOperations.tsx
src/components/QueryPanel/operations/WhereOperations.tsx
src/components/utils/fields.ts
src/components/utils/segment.ts

Calling `getOrAddDefaultSegment()` to interrogate a query can cause a mutation, so don't unless you mean to. This meant pushing the view or query object down instead of the segment.

Avoid calling getOrAddDefaultSegment unnecessarily

---

postcss.config.mjs

Not sure under what circumstances collisions are occurring, but move off the standard prefix.

Use our own css prefix

---

src/components/QueryPanel/AddMenu/AddAggregate.tsx
src/components/QueryPanel/AddMenu/AddEmptyNest.tsx
src/components/QueryPanel/AddMenu/AddFieldItem.tsx
src/components/QueryPanel/AddMenu/AddGroupBy.tsx
src/components/QueryPanel/AddMenu/AddLimit.tsx
src/components/QueryPanel/AddMenu/AddMenu.tsx
src/components/QueryPanel/AddMenu/AddOrderBy.tsx
src/components/QueryPanel/AddMenu/AddView.tsx
src/components/QueryPanel/AddMenu/AddWhere.tsx
src/components/QueryPanel/AddMenu/FieldList.tsx
src/components/QueryPanel/AddMenu/FieldMenu.tsx
src/components/QueryPanel/Operations.tsx
src/components/QueryPanel/Query.tsx
src/components/QueryPanel/View.tsx
src/components/QueryPanel/ViewDefinition.tsx
src/components/QueryPanel/operations/AggregateOperations.tsx
src/components/QueryPanel/operations/GroupByOperations.tsx
src/components/QueryPanel/operations/LimitOperation.tsx
src/components/QueryPanel/operations/NestOperation.tsx
src/components/QueryPanel/operations/OperationActionTitle.tsx
src/components/QueryPanel/operations/OrderByOperations.tsx
src/components/QueryPanel/operations/WhereOperations.tsx
src/components/utils/fields.ts
src/components/utils/segment.ts

Calling `getOrAddDefaultSegment()` to interrogate a query can cause a mutation, so don't unless you mean to. This meant pushing the view or query object down instead of the segment.

Avoid calling getOrAddDefaultSegment unnecessarily, take 2

---

src/components/filters/NumberFilterToken.tsx

Handle filters with multiple potential values differently from filters with only a single allowed value.

Fix an issue with switching number filter types

---

src/components/QueryPanel/operations/NestOperation.tsx

Right now, if you add a blank nested query, you have to manually expand it before adding content to it, because the action menu items are not visible while it is collapsed. Default it to expanded, because typically the nest action the user will want to take is interacting with it.

Default blank nested queries to be expanded

---

src/components/QueryPanel/AddMenu/AddMenu.tsx
src/components/utils/segment.ts

Since we should be applying and propagating default limits now, it doesn't make a lot of sense to add a `limit: 1000` (but only on group_by).
This also brings consistency to the different "add group by" flows, some of which do not include this logic today.
Followup to https://github.com/malloydata/malloy-explorer/pull/139

Remove the logic that adds a 1000 limit along with a group_by

---

src/components/ResultPanel/ResultDisplay.tsx
src/components/ResultPanel/result_display.css
src/components/primitives/DOMElement.tsx

The renderer was being rendered in a ScrollArea that was controlling the overflow. In order for row virtualization to work, the renderer has to be the one controlling its scroll container. This PR:
- updates the markup so that renderer is outside of a ScrollArea
- sets ResultDisplay to a CSS grid so the renderer height is constrained to available space instead of growing unbounded
- adds styling for the renderer to fill the width of ResultDisplay container, which makes for a better scrolling experience
Note that I had to import a css file instead of using stylex for adding the width to the malloy-render component, because I could not get stylex to support the `::part` selector. The build would fail with error "pseudo-class not recognized" when I tried using it in a style object.
Demo …

fix: renderer should virtualize

---

src/components/QueryPanel/AddMenu/FieldList.tsx
src/components/SourcePanel/utils.ts

Don't filter out arrays and records to allow group by for the top level field.

Allow group_by of arrays

---

dev/Source.tsx
dev/sample_models/example_model.ts
package-lock.json
package.json
src/components/DateInput.tsx
src/components/QueryPanel/DateLiteralEditor.tsx
src/components/QueryPanel/LiteralValueEditor.tsx
src/components/filters/DateTimeFilterCore.tsx
src/components/primitives/DatePicker.tsx

The native date picker was pretty disappointing to use, and didn't match our styling, use our own. Also switch from `moment()` to `moment.utc()` so our date stamps actually match. This is a going to require a change to our malloy generation code to correctly, since `timestamp_value: '1980-05-18 15:00:00',` produces `@1980-05-19 03:00:00` I might try to land that fix before landing this.

Use our date picker for parameters

---

src/components/SourcePanel/FieldTokenWithActions.tsx

Fix issue where hover actions hide when their tooltips are hovered, causing tooltips to detach and stick to the top left of the viewport. This fix ensures triggers remain visible when their tooltips are hovered.

Fix hover action tooltip

---

src/components/QueryPanel/Query.tsx

Annotation scoping means that top-level overrides of referenced views do not work.

Limit when vis editor appears

---

src/components/QueryPanel/AddMenu/AddOrderBy.tsx
src/components/SourcePanel/FieldTokenWithActions.tsx
src/components/SourcePanel/hooks/useOperations.ts
src/components/utils/fields.ts
src/components/utils/segment.spec.ts
src/components/utils/segment.ts
src/test/model.ts

Updates the Source Panel to include a "disabled reason" whenever the action button is disabled.
This also fixes a long tail of issues related to the use of Order By when there are duplicate field names (but different field paths):
Fixes broken behavior around Order By which became especially obvious whenever a joined-in table has the same field name as another field.
https://github.com/user-attachments/assets/b9304501-ae70-4b6c-b0bf-35a2b0d19426

Fix Source Panel order_by. Add disabled messages.

---

src/components/utils/filters.ts

For all string filter operators, negated operators are ignored while parsing filters to labels.

Fix filter label parser ignoring negated operators for string filters

---

dev/Query.tsx
src/components/CodeEditor/CodeEditor.tsx

Don't update query if query parsing fails, report errors if there are any, although we shouldn't get here if there are errors.

Better query conversion failure handling
