eslint.config.mjs
package-lock.json
package.json
src/components/Menu.tsx
src/components/QueryPanel/LiteralValueEditor.tsx
src/components/QueryPanel/Parameters.tsx
src/components/QueryPanel/ViewMenu.tsx
src/components/QueryPanel/operations/AggregateOperations.tsx
src/components/QueryPanel/operations/ClearButton.tsx
src/components/QueryPanel/operations/Field.tsx
src/components/QueryPanel/operations/GroupByOperations.tsx
src/components/QueryPanel/operations/LimitOperation.tsx
src/components/QueryPanel/operations/OrderByOperations.tsx
src/components/QueryPanel/operations/WhereOperations.tsx
src/components/QueryPanel/operations/hover.stylex.ts

@ntofigzade The hover styles stuff could probably be consolidated in component.

Switch to shared primitives where possible

---

src/components/Menu.tsx
src/components/QueryPanel/Query.tsx
src/components/QueryPanel/View.tsx
src/components/QueryPanel/ViewDefinition.tsx
src/components/QueryPanel/ViewMenu.tsx
src/components/QueryPanel/Visualization.tsx
src/components/primitives/Token.tsx
src/components/primitives/TokenGroup.tsx

@ntofigzade I had to do some tweaking to get styles applied with TokenGroups. Can't actually change visualization yet because of builder bug.

Query and visualization work

---

src/components/QueryPanel/operations/WhereOperations.tsx

Hack some prettier filter tokens for now.

Mock fancier filter tokens

---

src/components/primitives/Spinner.tsx
src/components/primitives/index.ts

Adds a 'Spinner' loading status indicator.

Spinner Primitive

---

src/components/primitives/SelectDropdown.tsx

Also remove duplicate DropdownMenu component.

Fix select dropdown

---

src/components/QueryPanel/ViewDefinition.tsx
src/components/QueryPanel/ViewMenu.tsx
src/components/QueryPanel/Visualization.tsx
src/components/ResultPanel/ViewAttributeTable.tsx
src/components/ResultPanel/Visualization.tsx
src/components/utils/renderer.ts

Add collapsing query preview.

---

dev/MalloyExplorer.tsx
dev/Primitives.tsx
dev/Query.tsx
dev/Result.tsx
dev/Source.tsx
dev/explorer.html
dev/index_app.ts
dev/index_primitives.ts
dev/primitives.html
dev/query.html
dev/result.css
dev/source.css
dev/source.html
dev/styles.css
index.html
src/components/QueryPanel/QueryActionBar.tsx
src/components/QueryPanel/QueryEditor.tsx
src/components/QueryPanel/QueryPanel.tsx
src/components/QueryPanel/index.ts
src/components/ResultPanel/ResultPanel.tsx
src/components/SourcePanel/SourcePanel.tsx

Add Query Panel wrapper component
Enhance UI

Refactor and stitch pieces together

---

src/components/QueryPanel/ViewMenu.tsx
src/components/QueryPanel/operations/WhereOperations.tsx
src/components/filters/BooleanFilterToken.tsx
src/components/filters/NumberFilterToken.tsx
src/components/filters/PillInput.tsx
src/components/filters/StringFilterToken.tsx

Add a rough draft of Number filters, along with some fixes to the String filters. I am continuing to iterate on this, but trying to merge frequently to avoid conflicts.

Initial implementation for Number Filters

---

src/components/QueryPanel/ViewMenu.tsx
src/components/QueryPanel/operations/WhereOperations.tsx
src/components/filters/DateTimeFilterToken.tsx

This is an initial checkin, with additional polish work to be done in a followup.

Initial implementation of Date/Time filters

---

src/components/QueryPanel/operations/ClearButton.tsx
src/components/QueryPanel/operations/WhereOperations.tsx
src/components/filters/DateTimeFilterToken.tsx

Plus add a tooltip to the 'X' button and allow date filters to operate on second precision

Make filters removable

---

src/components/QueryPanel/AddMenu/AddAggregate.tsx
src/components/QueryPanel/AddMenu/AddFieldItem.tsx
src/components/QueryPanel/AddMenu/AddGroupBy.tsx
src/components/QueryPanel/AddMenu/AddOrderBy.tsx
src/components/QueryPanel/AddMenu/AddView.tsx
src/components/QueryPanel/AddMenu/AddWhere.tsx

Refactor some duplicate code

---

src/components/QueryPanel/AddMenu/AddWhere.tsx
src/components/QueryPanel/QueryPanel.tsx
src/components/QueryPanel/operations/WhereOperations.tsx
src/components/filters/DateTimeFilterToken.tsx
src/components/primitives/DatePicker.tsx
src/components/primitives/ErrorIcon.tsx
src/components/primitives/NumberInput.tsx
src/components/primitives/tokens/EditableToken.tsx
src/components/primitives/tokens/SelectorToken.tsx

Makes a variety of improvements around date filters, including the ability to manually type a date. Fixes a wide range of bugs, issues and crashes.

Fix date picker focus issues

---

src/components/filters/NumberFilterToken.tsx

Update the Number Input to be more robust to removing values or adding incompatible text.

Fix issues with number filter

---

src/components/QueryPanel/operations/LimitOperation.tsx

Add an error message if limit is negative

Restrict limit to positive numbers

---

src/components/QueryPanel/AddMenu/AddFieldItem.tsx
src/components/QueryPanel/AddMenu/AddMenu.tsx
src/components/QueryPanel/Query.tsx
src/components/QueryPanel/operations/NestOperation.tsx
src/components/primitives/CollapsiblePanel.tsx

Move Add button to top so that it doesn't move as elements are added, and it doesn't cover the content.

Move Add button to top.

---

src/components/FieldToken.tsx
src/components/HoverCard.tsx
src/components/ResultPanel/ViewAttributeTable.tsx

Add preview to View hover cards

---

dev/MalloyExplorer.tsx
src/components/QueryPanel/QueryEditor.tsx
src/components/QueryPanel/QueryPanel.tsx

Used when source panel is visible.

Allow hiding source pane

---

src/components/QueryPanel/AddMenu/AddWhere.tsx

Pending fix in @malloydata/query-builder

Allow wheres from joins

---

src/components/QueryPanel/AddMenu/AddView.tsx
src/components/SourcePanel/utils.ts
src/components/utils/fields.ts

Used duck-typing to determine which views are index views.

Filter out index views

---

src/components/QueryPanel/AddMenu/AddAggregate.tsx
src/components/QueryPanel/AddMenu/AddFieldItem.tsx
src/components/QueryPanel/AddMenu/AddGroupBy.tsx
src/components/QueryPanel/AddMenu/AddMenu.tsx
src/components/QueryPanel/AddMenu/AddOrderBy.tsx
src/components/QueryPanel/AddMenu/AddView.tsx
src/components/QueryPanel/AddMenu/AddWhere.tsx
src/components/QueryPanel/AddMenu/FieldList.tsx
src/components/QueryPanel/AddMenu/FieldMenu.tsx
src/components/QueryPanel/AddMenu/ValueList.tsx
src/components/QueryPanel/operations/AggregateOperations.tsx
src/components/QueryPanel/operations/GroupByOperations.tsx
src/components/QueryPanel/operations/OperationActionTitle.tsx

Filter at the leafs instead of attempting to recursively pre-filter. useMemo() since even identical array results are not strictly equal.

Better dupe removal

---

src/components/QueryPanel/Parameters.tsx
src/components/QueryPanel/operations/AggregateOperations.tsx
src/components/QueryPanel/operations/GroupByOperations.tsx
src/components/QueryPanel/operations/NestOperation.tsx
src/components/QueryPanel/operations/OrderByOperations.tsx

Rather than just using array index, use a relatively static identifier from each element.

Use more meaningful key values

---

src/components/ResultPanel/ViewAttributeTable.tsx

Current thinking is that views will be treated as an output schema from which to work, not a set of tranformations over a source. Reflect this in the View display.

View Card Semantics

---

src/components/QueryPanel/QueryActionBar.tsx

Add a disabled reason to the run button

---

package.json
scripts/malloy-packages.ts
vite.config.mts

And properly extract malloy packages names

Add force malloy packages to be optimized

---

dev/MalloyExplorer.tsx
package-lock.json
src/components/QueryPanel/AddMenu/AddFieldItem.tsx
src/components/QueryPanel/AddMenu/AddItem.tsx
src/components/QueryPanel/AddMenu/AddMenu.tsx
src/components/QueryPanel/AddMenu/styles.ts
src/components/QueryPanel/FieldHover.tsx
src/components/QueryPanel/QueryActionBar.tsx
src/components/QueryPanel/operations/OperationActionTitle.tsx
src/components/primitives/Button.tsx
src/components/primitives/DropdownMenu.tsx
src/components/primitives/ErrorIcon.tsx
src/components/primitives/styles.ts
src/components/primitives/tokens/Token.tsx
src/stylex.css

Use portals to attach popup elements to the body, to consolidate styling.

Use portals

---

src/components/QueryPanel/AddMenu/AddAggregate.tsx
src/components/QueryPanel/AddMenu/AddEmptyNest.tsx
src/components/QueryPanel/AddMenu/AddFieldItem.tsx
src/components/QueryPanel/AddMenu/AddGroupBy.tsx
src/components/QueryPanel/AddMenu/AddLimit.tsx
src/components/QueryPanel/AddMenu/AddMenu.tsx
src/components/QueryPanel/AddMenu/AddOrderBy.tsx
src/components/QueryPanel/AddMenu/AddView.tsx
src/components/QueryPanel/AddMenu/AddWhere.tsx
src/components/QueryPanel/AddMenu/FieldList.tsx
src/components/QueryPanel/AddMenu/FieldMenu.tsx
src/components/QueryPanel/Operations.tsx
src/components/QueryPanel/Query.tsx
src/components/QueryPanel/operations/AggregateOperations.tsx
src/components/QueryPanel/operations/GroupByOperations.tsx
src/components/QueryPanel/operations/LimitOperation.tsx
src/components/QueryPanel/operations/NestOperation.tsx
src/components/QueryPanel/operations/OperationActionTitle.tsx
src/components/QueryPanel/operations/OrderByOperations.tsx
src/components/QueryPanel/operations/WhereOperations.tsx
src/components/utils/fields.ts
src/components/utils/segment.ts

Reverts malloydata/malloy-explorer#140

Revert "Avoid calling getOrAddDefaultSegment unnecessarily"

---

babel.config.mjs
postcss.config.mjs

Fix custom css prefixing

---

babel.config.mjs

Somehow messes up vite dev mode.

Don't change prefix for now

---

src/components/DateInput.tsx
src/components/filters/DateTimeFilterCore.tsx
src/components/filters/hooks/useFilterModal.tsx

Date filter

---

src/components/filters/BooleanFilterCore.tsx

Re-use operator values for filter type.

Simplify boolean login

---

src/components/QueryPanel/AddMenu/FieldList.tsx
src/components/SourcePanel/utils.ts

Reverts malloydata/malloy-explorer#192

Revert "Convert arrays of records and records into join like objects."

---

dev/Result.tsx
src/components/FieldHoverCard.tsx
src/components/ResultPanel/ResultDisplay.tsx
src/components/ResultPanel/RunInfoHover.tsx
src/components/ResultPanel/SubmittedQuery.ts
src/components/primitives/HoverCard.tsx
src/index.ts

Reverts malloydata/malloy-explorer#184
Sorry about that.

Revert "Revert "query info display""

---

src/components/FieldHoverCard.tsx
src/components/primitives/HoverText.tsx

At least compatible with Chrome and Safari

View annotations must truncate after third line

---

src/components/QueryPanel/AddMenu/AddAggregate.tsx
src/components/QueryPanel/AddMenu/AddFieldItem.tsx
src/components/QueryPanel/AddMenu/AddGroupBy.tsx
src/components/QueryPanel/AddMenu/AddMenu.tsx
src/components/QueryPanel/AddMenu/AddView.tsx
src/components/QueryPanel/AddMenu/AddWhere.tsx
src/components/ResultPanel/EmptyQueryDisplay.tsx
src/components/SourcePanel/SourcePanel.tsx
src/components/utils/annotations.ts
src/components/utils/fields.ts

As per request from @nachoarreola 
Haven't touched Source/Query a ton -  @ntofigzade @whscullin please let me know if I missed any cases/if there's a better way to do this. Thanks!

support for filtering tagged "no ui" fields

---

dev/Query.tsx
package-lock.json
package.json
src/components/QueryPanel/Operations.tsx
src/components/QueryPanel/operations/AggregateOperations.tsx
src/components/QueryPanel/operations/GroupByOperations.tsx
src/components/QueryPanel/operations/SortableOperations.tsx
src/components/primitives/tokens/Token.tsx

Allow drag and drop of dimensions and measures within a query.

---

src/components/QueryPanel/AddMenu/AddAggregate.tsx
src/components/QueryPanel/AddMenu/AddGroupBy.tsx
src/components/QueryPanel/AddMenu/AddMenu.tsx
src/components/QueryPanel/AddMenu/AddView.tsx
src/components/QueryPanel/Operations.tsx
src/components/QueryPanel/Query.tsx
src/components/QueryPanel/operations/NestOperation.tsx
src/components/QueryPanel/operations/OperationActionTitle.tsx
src/components/QueryPanel/operations/RenameDialog.tsx
src/components/QueryPanel/operations/SortableOperations.tsx
src/components/SourcePanel/FieldTokenWithActions.tsx
src/components/SourcePanel/NestFieldDropdownMenu.tsx
src/components/SourcePanel/OperationDropdownMenuItems.tsx
src/components/SourcePanel/hooks/useOperations.ts
src/components/primitives/ErrorIcon.tsx
src/components/utils/fields.ts
src/components/utils/segment.ts

Add support for renaming fields, plus allow any field not already in the current segment to be added and rename it if there is an output schema collision.

Renaming and duplicate handling

---

src/components/QueryPanel/AddMenu/FieldList.tsx
src/components/QueryPanel/AddMenu/FieldMenu.tsx
src/components/QueryPanel/AddMenu/styles.ts
src/components/filters/StringFilterCore.tsx

Fixing the FieldList component to 50vh max height broke the search view of the add menu. Moved further up in layout. Removed ScrollableAreas because they are not recommended for this purpose.

Fix overlapping fields in search

---

src/components/filters/DateTimeFilterCore.tsx

Our oddball formats like weeks and quarter were blowing up.

Use unit formatting

---

src/components/filters/DateTimeFilterCore.tsx

Handle transitioning units for `before`, `after`, `to` and `in`

Better date handling

---

package-lock.json
package.json
src/components/FieldToken.tsx
src/components/QueryPanel/operations/SortableOperations.tsx
src/components/utils/segment.ts

Needs https://github.com/malloydata/malloy/pull/2321

Granularity

---

src/components/QueryPanel/ViewDefinition.tsx
src/components/QueryPanel/operations/NestOperation.tsx
src/components/ResultPanel/ViewAttributeTable.tsx
src/components/primitives/CollapsiblePanel.tsx

- Nested sections should default to open
- Remove ScrollableArea to fix overflow in ViewAttributeTable

Nested sections should default to open

---

src/components/FieldHoverCard.tsx
src/components/primitives/HoverText.tsx
src/components/primitives/RichText.tsx

Fixes disappearing hovertext tooltip when being hovered
Adding rich text component to display links

Fix hover text and add RichText component

---

.github/workflows/test.yaml
.gitignore
jest.config.ts
package-lock.json
package.json
src/components/utils/fields.ts
src/components/utils/segment.spec.ts
src/test/jest.setup.ts
src/test/model.ts
src/test/utils.ts

A journey of a thousand miles...

Bootstrap tests

---

package-lock.json
package.json
src/components/QueryPanel/Query.tsx

Re-enable viz editing for queries because of https://github.com/malloydata/malloy/pull/2326

Malloy 0.0.277

---

.gitmodules
README.md
dev/MalloyExplorer.tsx
dev/utils/runtime.ts
package-lock.json
package.json
src/components/QueryPanel/operations/DrillOperations.tsx
src/components/QueryPanel/operations/FilterOperations.tsx
tsconfig.json
vite.config.mts

Switch to compiling and running queries in the explorer dev panel. Uses `malloy-samples` as a submodule to allow for more varied test scenarios.

Apply drilling fixes in Malloy 0.0.295.
